spring.application.name=cadastro
server.address=127.0.0.1
server.port=${PORT:8080}
spring.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/cadastro_lab}
lab.aws-endpoint=${AWS_ENDPOINT:http://127.0.0.1:4566}
lab.topic-arn=arn:aws:sns:us-east-1:000000000000:cadastro-solicitado
lab.queue-url=${SQS_QUEUE_URL:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/cadastro-solicitado}
